name: agora_wrapper
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  provider: ^5.0.0
  tuple: ^2.0.0
  json_annotation: ^4.8.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  fluttertoast: 8.1.0
  agora_rtc_engine: 6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.typing.agora_wrapper.agora_wrapper
        pluginClass: AgoraWrapperPlugin
      ios:
        pluginClass: AgoraWrapperPlugin
        
  assets:
    - lib/faceunity/ui/resource/
    - lib/faceunity/ui/resource/sticker/
    - lib/faceunity/ui/resource/sticker/stickers.json
    - lib/faceunity/ui/resource/sticker/2.0x/
    - lib/faceunity/ui/resource/sticker/3.0x/
    - lib/faceunity/ui/resource/skin/
    - lib/faceunity/ui/resource/skin/2.0x/
    - lib/faceunity/ui/resource/skin/3.0x/
    - lib/faceunity/ui/resource/shape/
    - lib/faceunity/ui/resource/shape/2.0x/
    - lib/faceunity/ui/resource/shape/3.0x/
    - lib/faceunity/ui/resource/filter/
    - lib/faceunity/ui/resource/filter/2.0x/
    - lib/faceunity/ui/resource/filter/3.0x/
    - lib/faceunity/ui/resource/makeup/
    - lib/faceunity/ui/resource/makeup/2.0x/
    - lib/faceunity/ui/resource/makeup/3.0x/
    - lib/faceunity/ui/resource/body/
    - lib/faceunity/ui/resource/body/2.0x/
    - lib/faceunity/ui/resource/body/3.0x/
    - lib/faceunity/ui/resource/common/
    - lib/faceunity/ui/resource/common/2.0x/
    - lib/faceunity/ui/resource/common/3.0x/

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
